FROM node:12.15.0-alpine as app_build

ARG api_endpoint

WORKDIR /home/app
COPY public ./public
COPY src ./src
COPY package.json ./package.json
RUN npm install
ENV REACT_APP_API_ENDPOINT=${api_endpoint}
RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY --from=app_build /home/app/build .
EXPOSE 80