version: "2.0"

services:

    database:
        container_name: ssp3_database
        image: mysql:5.6
        environment: 
            MYSQL_ROOT_PASSWORD: password1234
            MYSQL_DATABASE: ssp3
            MYSQL_USER: user_dev
            MYSQL_PASSWORD: 1234
        ports: 
            - "3306:3306"
        volumes: 
            - ./api/mysql_data:/var/lib/mysql
    
    phpmyadmin:
        container_name: ssp3_phpma
        image: phpmyadmin/phpmyadmin:4.9
        ports: 
            - "8080:80"
        environment: 
            PMA_HOST: database
            PMA_USER: user_dev
            PMA_PASSWORD: 1234

    api:
        container_name: ssp3_api
        build: 
            context: ./api
            dockerfile: Dockerfile-prod
        restart: on-failure
        volumes: 
            - /home/api/node_modules
        environment: 
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            API_SECRET: ${API_SECRET}
            EMAIL_SECRET: myemailsecretkeyfortoken
            MAIL_LOGIN: jwp7bw3ypsxhc3n6@ethereal.email
            MAIL_USER: jwp7bw3ypsxhc3n6@ethereal.email
            MAIL_PASSWORD: g8qC37Fxx5PhT9HrzA
            MAIL_SERVICE_PORT: 587
            MAIL_SERVICE_HOST: smtp.ethereal.email
            NODE_ENV: production
        ports:
            - 80:3002
        command: npm run start-prod

    app:
        container_name: ssp3_app
        build: 
            context: ./client
            dockerfile: Dockerfile-prod
            args: 
                api_endpoint: "http://${MACHINE_HOST}"
        ports: 
            - 80:80
        volumes: 
            - /home/app/node_modules        
