---
- name: "[BACKOFFICE] Copy env file for docker-compose"
  become: true
  template:
    src: "container-app-env.j2"
    dest: "{{ web_server_workdir }}/{{ web_server_repo_dirname }}/.env"

- name: "[BACKOFFICE] - start docker-compose app"
  become: true
  shell: "cd {{ web_server_workdir }}/{{ web_server_repo_dirname }} && sudo docker-compose -f {{ web_server_docker_compose_file }} up -d app"
  register: output