---
# tasks file for dbmysql
- name: "[DBMYSQL] - start docker-compose database"
  become: true
  shell: "cd {{ web_server_workdir }}/{{ web_server_repo_dirname }} && sudo docker-compose -f {{ web_server_docker_compose_file }} up -d database phpmyadmin"
  register: output