all:
    children:
        backoffice:
            hosts:
                35.180.83.1:
        api:
            hosts:
                15.236.186.226:
                35.180.231.152:
        dbmysql:
            hosts:
                35.180.137.169:
        haproxy_api:
            hosts:
                15.188.193.168:
