---
# tasks file for api

- name: "[API] Copy env file for docker-compose"
  become: true
  template:
    src: container-api-env.j2
    dest: "{{ web_server_workdir }}/{{ web_server_repo_dirname }}/.env"
  tags:
    - first-deploy

- name: "[API] - git pull"
  become: true
  shell: "cd {{ web_server_workdir }}/{{ web_server_repo_dirname }} && sudo git pull origin prod"
  register: output
  tags:
    - cd-deploy

- name: "[API] - docker down"
  become: true
  shell: "cd {{ web_server_workdir }}/{{ web_server_repo_dirname }} && sudo docker-compose -f {{ web_server_docker_compose_file }} down api"
  register: output
  tags:
    - cd-deploy

- name: "[API] - start docker-compose api"
  become: true
  shell: "cd {{ web_server_workdir }}/{{ web_server_repo_dirname }} && sudo docker-compose -f {{ web_server_docker_compose_file }} up --force-recreate --build -d api"
  register: output
  tags:
    - first-deploy
    - cd-deploy
    