---
# tasks file for api

- name: "[API] Copy env file for docker-compose"
  become: true
  template:
    src: container-api-env.j2
    dest: "{{ web_server_workdir }}/{{ web_server_repo_dirname }}/.env"

- name: "[API] - start docker-compose api"
  become: true
  shell: "cd {{ web_server_workdir }}/{{ web_server_repo_dirname }} && sudo docker-compose -f {{ web_server_docker_compose_file }} up -d api"
  register: output