# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: "test test"
      run: |
        echo "iciiiiiii"
        echo ${{secrets.SSP3_HOSTS_KEY}}

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.1.1
      with:
        # Ansible playbook filepath
        playbook: playbook.yml
        # Root directory of Ansible project (defaults to current)
        directory: ansible
        # SSH private key used to connect to the host
        key: ${{secrets.SSP3_HOSTS_KEY}}
        # Extra options that should be passed to ansible-playbook command
        options: |
          --tags cd-deploy
          -i hosts.yml
          --verbose
          -u ubuntu
